# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: broker.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import tco_tmiv_pb2 as tco__tmiv__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0c\x62roker.proto\x12\x06\x62roker\x1a\x0etco_tmiv.proto"0\n\x12PostCommandRequest\x12\x1a\n\x03tco\x18\x03 \x01(\x0b\x32\r.tco_tmiv.Tco"\x15\n\x13PostCommandResponse"\x16\n\x14\x43ommandStreamRequest"E\n\x15\x43ommandStreamResponse\x12\x10\n\x08tco_json\x18\x01 \x01(\t\x12\x1a\n\x03tco\x18\x02 \x01(\x0b\x32\r.tco_tmiv.Tco"G\n\x14PostTelemetryRequest\x12\x11\n\ttmiv_json\x18\x01 \x01(\t\x12\x1c\n\x04tmiv\x18\x02 \x01(\x0b\x32\x0e.tco_tmiv.Tmiv"\x17\n\x15PostTelemetryResponse"\x18\n\x16TelemetryStreamRequest"7\n\x17TelemetryStreamResponse\x12\x1c\n\x04tmiv\x18\x03 \x01(\x0b\x32\x0e.tco_tmiv.Tmiv"9\n\x1fGetLastReceivedTelemetryRequest\x12\x16\n\x0etelemetry_name\x18\x01 \x01(\t"@\n GetLastReceivedTelemetryResponse\x12\x1c\n\x04tmiv\x18\x01 \x01(\x0b\x32\x0e.tco_tmiv.Tmiv2\xbd\x03\n\x06\x42roker\x12\x46\n\x0bPostCommand\x12\x1a.broker.PostCommandRequest\x1a\x1b.broker.PostCommandResponse\x12X\n\x13OpenTelemetryStream\x12\x1e.broker.TelemetryStreamRequest\x1a\x1f.broker.TelemetryStreamResponse0\x01\x12m\n\x18GetLastReceivedTelemetry\x12\'.broker.GetLastReceivedTelemetryRequest\x1a(.broker.GetLastReceivedTelemetryResponse\x12T\n\x11OpenCommandStream\x12\x1c.broker.CommandStreamRequest\x1a\x1d.broker.CommandStreamResponse(\x01\x30\x01\x12L\n\rPostTelemetry\x12\x1c.broker.PostTelemetryRequest\x1a\x1d.broker.PostTelemetryResponseb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "broker_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _POSTCOMMANDREQUEST._serialized_start = 40
    _POSTCOMMANDREQUEST._serialized_end = 88
    _POSTCOMMANDRESPONSE._serialized_start = 90
    _POSTCOMMANDRESPONSE._serialized_end = 111
    _COMMANDSTREAMREQUEST._serialized_start = 113
    _COMMANDSTREAMREQUEST._serialized_end = 135
    _COMMANDSTREAMRESPONSE._serialized_start = 137
    _COMMANDSTREAMRESPONSE._serialized_end = 206
    _POSTTELEMETRYREQUEST._serialized_start = 208
    _POSTTELEMETRYREQUEST._serialized_end = 279
    _POSTTELEMETRYRESPONSE._serialized_start = 281
    _POSTTELEMETRYRESPONSE._serialized_end = 304
    _TELEMETRYSTREAMREQUEST._serialized_start = 306
    _TELEMETRYSTREAMREQUEST._serialized_end = 330
    _TELEMETRYSTREAMRESPONSE._serialized_start = 332
    _TELEMETRYSTREAMRESPONSE._serialized_end = 387
    _GETLASTRECEIVEDTELEMETRYREQUEST._serialized_start = 389
    _GETLASTRECEIVEDTELEMETRYREQUEST._serialized_end = 446
    _GETLASTRECEIVEDTELEMETRYRESPONSE._serialized_start = 448
    _GETLASTRECEIVEDTELEMETRYRESPONSE._serialized_end = 512
    _BROKER._serialized_start = 515
    _BROKER._serialized_end = 960
# @@protoc_insertion_point(module_scope)
